### ISSUE TITLE
Crash on startup in Debian 11 (amd64)

### ISSUE THREAD

**Issue by mbrethes** [TheFlav/Flash-Masta-Desktop#3]
After following the complete compilation procedure, FlashMasta does a segfault upon startup, whether the cart is plugged to the USB cable or not.

**Comment by mbrethes** [comment]
The precompiled Manjaro version downloaded [here](http://www.flashmasta.com/software-downloads/) works perfectly tho.

**Comment by mbrethes** [comment]
Is there any debug mode to extract more information before the crash?

**Comment by TheFlav** [comment]
Try running under sudu (or root account)Sent from my iPhone. On Nov 6, 2022, at 8:38 AM, Mathieu Brèthes ***@***.***> wrote:﻿
Is there any debug mode to extract more information before the crash?

**Comment by mbrethes** [comment]
The precompiled version works without sudo ^^. So I expect the one I compiled myself, to also run without sudo...

Anyway, I managed to get a stack trace:

```
Thread 1 "FlashMasta" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff6fa3cc5 in QCoreApplication::arguments() ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff390b793 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#3  0x00007ffff390bf03 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007ffff312841c in _SmcProcessMessage () at /lib/x86_64-linux-gnu/libSM.so.6
#5  0x00007ffff31166f6 in IceProcessMessages () at /lib/x86_64-linux-gnu/libICE.so.6
#6  0x00007ffff6fd65e0 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff6fd99df in QSocketNotifier::activated(QSocketDescriptor, QSocketNotifier::Type, QSocketNotifier::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff6fda1db in QSocketNotifier::event(QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff7a6215f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff6f9ffca in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff6ff80d5 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff5e80e6b in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff5e81118 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff5e811cf in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff6ff751f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6f9e98b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff6fa6c00 in QCoreApplication::exec() ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x0000555555573511 in main(int, char**) (argc=1, argv=0x7fffffffe1d8)
    at ../src/ui/qt/main.cpp:9

```
If that can be of any help...

To reproduce:

Add:
    DEFINES += "MIN_LOG_LEVEL=log_level::DEBUG"
    QMAKE_CXXFLAGS += -g

to FlashMasta.pro

Build.

Run `gdb FlashMasta`

Then type "bt" when segfault shows up.
